server:
  port: 8083

spring:
  application:
    name: budget-service
  
  datasource:
    url: jdbc:mysql://localhost:3306/budget_db
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

jwt:
  secret: mySecretKey123456789012345678901234567890

# Budget specific configuration
budget:
  alert:
    threshold: 80  # Alert when 80% of budget is spent
  scheduler:
    enabled: true  # Enable/disable all scheduled jobs

# External service URLs
services:
  expense-service:
    url: http://localhost:8082

logging:
  level:
    com.expensetracker: DEBUG
    org.springframework.security: DEBUG
    org.springframework.scheduling: DEBUG

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Enable scheduling
spring.task.scheduling.enabled: true

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/budget_db

services:
  expense-service:
    url: http://expense-service:8082